export const AUTH_API_ENDPOINT = "https://job-seeking-app-1-5auy.onrender.com/api/v1/user"
export const JOBSEEKER_API_ENDPOINT = "https://job-seeking-app-1-5auy.onrender.com/api/v1/jobseeker"
export const JOBGIVER_API_ENDPOINT = "https://job-seeking-app-1-5auy.onrender.com/api/v1/jobgiver"
export const JOB_API_ENDPOINT = "https://job-seeking-app-1-5auy.onrender.com/api/v1/job"
export const APPLICATION_API_ENDPPOINT = "https://job-seeking-app-1-5auy.onrender.com/api/v1/application"